carts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("cart", views.view, name="cart"),
    path('cart/<int:id>/', views.update_cart, name='update_cart'),
]

orders/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("checkout", views.checkout, name="checkout"),
    path("orders", views.orders, name="user_orders"),
    path("all-orders", views.all_orders, name="all_orders"),

]

pizza/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("", include("orders.urls")),
    path("", include("carts.urls")),
    path("", include("products.urls")),
]
# urlpatterns += i18n_patterns(
#     path("", include("accounts.urls")),
#     prefix_default_language=False,
# )
# urlpatterns += i18n_patterns(
#     path("", include("orders.urls")),
#     prefix_default_language=False,
# )
# urlpatterns += i18n_patterns(
#     path("", include("carts.urls")),
#     prefix_default_language=False,
# )
# urlpatterns += i18n_patterns(
#     path("", include("products.urls")),
#     prefix_default_language=False,
# )

carts/models.py
from django.db import models
from products.models import *

# Create your models here.

class CartItem(models.Model):
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    size = models.CharField(max_length=64)
    price = models.DecimalField(default="0.00", max_digits=6, decimal_places=2)
    line_total = models.DecimalField(default="0.00", max_digits=6, decimal_places=2)
    topping1 = models.CharField(max_length=64, null=True, blank=True)
    topping2 = models.CharField(max_length=64, null=True, blank=True)
    topping3 = models.CharField(max_length=64, null=True, blank=True)

    def __str__(self):
        try:
            return str(self.cart.id)
        except:
            return f"{self.product.kind} {self.product.variation} {self.product.size}"

class Cart(models.Model):
    total = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "Cart id: %s" %(self.id)

orders/models.py
from django.db import models

# Create your models here.
from carts.models import Cart
from django.contrib.auth.models import User

class Status(models.Model):
    title = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.title}"

class Order(models.Model):
    order_id = models.CharField(max_length=64, default='ABC', unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.order_id

orders/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail

# Create your views here.

from carts.models import Cart
from .models import Order, Status
from .utils import id_generator

@login_required
def orders(request):

    context = {
    }
    return render(request, "orders/user.html", context)

@login_required
def all_orders(request):

    statuses = Status.objects.all()
    all_orders = Order.objects.all()

    context = {
        "all_orders": all_orders,
        "statuses": statuses
    }
    
    if request.method == "POST" and request.user.is_staff:
        for statuse in statuses:
            order_to_change = request.POST.get(str(statuse))
            if order_to_change:
                order = Order.objects.get(order_id=order_to_change)
                order.status = statuse
                order.save()
                return render(request, "orders/all.html", context)
            else:
                continue
        try:
            fil = request.POST.get('filter')
            if fil == "All Orders":
                return render(request, "orders/all.html", context)
            else:
                all_orders = Order.objects.filter(status__title=fil)
                print(all_orders)
                context["all_orders"] = all_orders
                context["fil"] = fil
                return render(request, "orders/all.html", context)
        except:
            return render(request, "orders/all.html", context)
    elif request.user.is_staff:
        return render(request, "orders/all.html", context)
    else:
        return render(request, "orders/user.html", context)

@login_required
def checkout(request):

    try:
        the_id = request.session['cart_id']
        cart = Cart.objects.get(id=the_id)
    except:
        the_id = None
        return HttpResponseRedirect(reverse("cart"))

    try:
        new_order = Order.objects.get(cart=cart, user=request.user)
    except Order.DoesNotExist:
        new_order = Order(cart=cart, user=request.user, status=Status.objects.get(title="Pending"))
        new_order.order_id = id_generator()
        new_order.save()
        del request.session['cart_id']
        del request.session['items_total']
        # send_mail("Order created", "Hi! Your order has been created successfully", "smolestan@gmail.com", ["smolestan@gmail.com"], fail_silently=False)
        return HttpResponseRedirect(reverse("user_orders"))

    context = {
        "user": request.user,
    }
    return render(request, "products/index.html", context)

orders/templates/orders/all.html
{% extends "products/base.html" %}
{% load i18n %}
{% block title %}
{% trans "Pinocchio's Pizza & Subs" %}
{% endblock %}

{% block body %}

{% include "products/navbar.html" %}

<div class="container">

    {% if empty %}

    <h1> {{ empty_message }}</h1>

    {% else %}

        <form name=filterform class="form m-3" method='POST' action='{% url "all_orders" %}'>
            {% csrf_token %}
            <div class="dropdown">
                <button class="btn btn-outline-info dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {% if fil %}
                        {{ fil }}
                    {% else %}
                    {% trans "All Orders" %}
                    {% endif %}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <button class="dropdown-item" name="filter" type="submit"
                        value="All Orders">{% trans "All Orders" %}</button>
                    {% for statuse in statuses %}
                    <button class="dropdown-item" name="filter" type="submit"
                        value="{{ statuse }}">{{ statuse }}</button>
                    {% endfor %}
                </div>
            </div>
        </form>
        <table class="table">

            <thead>
                <th>{% trans "Orders" %}</th>
                <th>{% trans "Customer" %}</th>
                <th>{% trans "Total" %}</th>
                <th>{% trans "Created" %}</th>
                <th>{% trans "Status" %}</th>
            </thead>
            {% for item in all_orders %}
            <tr>
                <td>
                    {% trans "Order #" %}{{ item.order_id }}


                    <ul>
                        {% for item in item.cart.cartitem_set.all %}

                        <li>
                            {{ item.quantity }} {{ item.size }} {{ item.product }} {% trans "for" %} ${{ item.line_total }}

                            <ul>
                                {% if item.topping1 %}
                                <li>{{ item.topping1 }}</li>
                                {% endif %}
                                {% if item.topping2 %}
                                <li>{{ item.topping2 }}</li>
                                {% endif %}
                                {% if item.topping3 %}
                                <li>{{ item.topping3 }}</li>
                                {% endif %}
                            </ul>

                        </li>

                        {% endfor %}
                    </ul>
                <td class="align-middle">
                    {{ item.user }}
                </td>
                <td class="align-middle">
                    ${{ item.cart.total }}
                </td>

                </td>
                <td class="align-middle">
                    {{ item.timestamp }}
                </td>

                <td class="align-middle">
                    <form name=statusform class="form" method='POST' action='{% url "all_orders" %}'>
                        {% csrf_token %}
                        <div class="dropdown">
                            <button class="btn btn-info dropdown-toggle btn-block" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ item.status }}
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                {% for statuse in statuses %}
                                <button class="dropdown-item" name="{{ statuse }}" type="submit"
                                    value="{{item}}">{{ statuse }}</button>
                                {% endfor %}
                            </div>
                        </div>
                    </form>
                </td>

            </tr>
            {% endfor %}
        </table>





        {% endif %}

        {% endblock %}

orders/templates/orders/user.html
{% extends "products/base.html" %}
{% load i18n %}
{% block title %}
{% trans "Pinocchio's Pizza & Subs" %}
{% endblock %}

{% block body %}

{% include "products/navbar.html" %}

<div class="container">

    {% if empty %}

    <h1> {{ empty_message }}</h1>

    {% else %}

    <table class="table">

        <thead>
            <th>{% trans "Orders" %}</th>
            <th>{% trans "Total" %}</th>
            <th>{% trans "Created" %}</th>
            <th>{% trans "Status" %}</th>
        </thead>
        {% for item in request.user.order_set.all %}
        <tr>
            <td>
                {% trans "Order #" %}{{ item.order_id }}


                <ul>
                    {% for item in item.cart.cartitem_set.all %}

                    <li>
                        {{ item.quantity }} {{ item.size }} {{ item.product }} {% trans "for" %} ${{ item.line_total }}

                        <ul>
                            {% if item.topping1 %}
                            <li>{{ item.topping1 }}</li>
                            {% endif %}
                            {% if item.topping2 %}
                            <li>{{ item.topping2 }}</li>
                            {% endif %}
                            {% if item.topping3 %}
                            <li>{{ item.topping3 }}</li>
                            {% endif %}
                        </ul>

                    </li>

                    {% endfor %}
                </ul>
            <td class="align-middle">
                ${{ item.cart.total }}
            </td>

            </td>
            <td class="align-middle">
                {{ item.timestamp }}
            </td>
            <td class="align-middle">
                {{ item.status }}
            </td>

        </tr>
        {% endfor %}
    </table>





    {% endif %}

    {% endblock %}